version: '3.8'

services:

  docker-mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: wallet_microservice
      MYSQL_ROOT_PASSWORD: root
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
#      - ./root/schema.sql:/docker-entrypoint-initdb.d/schema.sql
#      - /root/app/schema.sql:/docker-entrypoint-initdb.d/schema.sql
#      - ./src/main/resources/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

       - /schema.sql:/docker-entrypoint-initdb.d/schema.sql

  myapp:
#    build:
#      dockerfile: Dockerfile
    image: eclipse-temurin:21
    command: ["java", "-jar", "/app/app.jar"]
    volumes:
      - /app.jar:/app/app.jar
    ports:
      - "8090:8080"

    depends_on:
      docker-mysql:
        condition: service_healthy